### ISSUE TITLE
WebMercatorViewport.fitBounds() api is out of date vs. new changes to fitBounds() in 6.2.0

### ISSUE THREAD

**Issue by apete343** [uber-common/viewport-mercator-project#101]
The [docs for `WebMercatorViewport.fitBounds()`](https://github.com/uber-common/viewport-mercator-project/blob/master/docs/api-reference/web-mercator-viewport.md#fitboundsbounds-options) state that the `bounds` parameter is:
> ([[Number,Number],[Number,Number]]) - an array of two opposite corners of the bounding box. Each corner is specified in [lon, lat].

According to these docs, the `bounds` are not order-dependent.

However, with the [changes in 6.2.0 to the underlying `fitBounds()` function](https://github.com/uber-common/viewport-mercator-project/pull/93/files#diff-71d83ae31d13977684edd8fd1e830703R70), `WebMercatorViewport.fitBounds()` no longer works as expected if you supply the northeast bound first and do not provide a `minExtent`. `Math.max()` will select the new `minExtent` parameter (value of `0`), since the value of the bound difference will be negative.

**Comment by ibgreen** [comment]
@apete343 Yes. Sounds like adding `Math.abs()` in two places would fix this. 

Would you be willing to put up a PR with a test case covering the reverse order and the change?

I can publish a patch once landed.

**Comment by apete343** [comment]
@ibgreen sure sounds good
