### ISSUE TITLE
`assert` is a required module but not specified in the package.json

### ISSUE THREAD

**Issue by vicapow** [uber-common/viewport-mercator-project#33]
see: https://github.com/uber-common/viewport-mercator-project/blob/335cf91cbd6a9446923df1db049a34e4c5d337d5/src/perspective-mercator-viewport.js#L4

This is breaking my react-native project

**Comment by ibgreen** [comment]
> `assert` is a required module but not specified in the package.json

@vicapow Hmm, `assert` is not supposed to be included in package.json. It is a built in module that is supplied by node or the bundler (browserify, webpack, rollup). If the build process you use for `react-native` doesn't have an option to supply it you will have an issue with many packages, not just this one.

Alternative solutions: 
* set up an alias in your webpack config and provide your own empty function
* there are webpack and browserify transforms for removing assert
* pin `viewport-mercator-project` to version 1 or 2.

**Comment by vicapow** [comment]
This is the first module I've run into like this so I'm not sure it's a general issue for most projects.

What does assert offer beyond an extra dependency for this project that a `throw new Error(...)` couldn't solve?

Grepping through the project, I've only seen it used as a function with no message. Would you accept a PR if I remove the dependency and replace uses with `throw` and a meaningful error message?

**Comment by vicapow** [comment]
Alternatively, we could add the dependency to commonjs "assert" https://github.com/defunctzombie/commonjs-assert

One more point for color because we just ran into this related issue recently. Without specifying the dependency explicitly you run the risk of inconsistent implementations. This is the case with the querystring built in Node module and the browserify version that hasn't been updated in several years: https://www.npmjs.com/package/querystring

**Comment by TrySound** [comment]
I think this is not relevant anymore
/cc @Pessimistress

**Comment by PrimeTimeTran** [comment]
@TrySound Could I recommend opening this backup? I'm running into this problem myself.
```
"react-map-gl": "^4.1.2",
```
https://www.youtube.com/watch?v=FR3ti0UmUaA&feature=youtu.be

**Comment by TrySound** [comment]
@PrimeTimeTran This is different problem. You get custom assertion error, not the error about missing not assert module.
