### ISSUE TITLE
Examples, especially for PerspectiveMercatorViewport

### ISSUE THREAD

**Issue by gavinpatkinson** [uber-common/viewport-mercator-project#35]
I can't seem to find any examples on PerspectiveMercatorViewport usage.

**Comment by ibgreen** [comment]
@gavinpatkinson This viewport class is used extensively in [react-map-gl](https://github.com/uber/react-map-gl/search?utf8=%E2%9C%93&q=PerspectiveMercatorViewport&type=). 

Also, there is a similar class in deck.gl, the [WebMercatorViewport](https://github.com/uber/deck.gl/blob/4.1-release/src/lib/viewports/web-mercator-viewport.js)) which is essentially a fork of the `PerspectiveMercatorViewport`, extensively used in the examples in that framework.
