### ISSUE TITLE
API audit

### ISSUE THREAD

**Issue by Pessimistress** [uber-common/viewport-mercator-project#41]
Overall, I suggest we remove "mercator" keyword from function names since the whole module is about mercator projection.

 - `projectFlat`
 - `unprojectFlat`
 - `getMercatorMeterZoom` -> `getMeterZoom`
 - `getMercatorDistanceScales` -> `getDistanceScales`
 - `getMercatorWorldPosition` -> `getWorldPosition`
 - `makeViewMatricesFromMercatorParams` -> `getViewMatrix` (return single matrix instead of object)
 - `makeUncenteredViewMatrixFromMercatorParams` -> `getUncenteredViewMatrix`
 - `makeProjectionMatrixFromMercatorParams` -> `getProjectionMatrix`
 - `getFov`
 - `getClippingPlanes`
- `fitBounds`

@ib

**Comment by ibgreen** [comment]
+1 to this, except I think the `makeMakeViewMatrices` was written that way to avoid double calculation of the matrix. 

We could offer separate versions I suppose, but not sure it is worth the trouble to remove the combined one at this stage.

**Comment by Pessimistress** [comment]
At the moment `WebMercatorViewport` in this module and deck.gl are the only users of these utils. I can confirm that there will be no double calculation if we remove the combined function.
