### ISSUE TITLE
Fitting to bounds provided by `unproject` yields strange results

### ISSUE THREAD

**Issue by Jivings** [uber-common/viewport-mercator-project#50]
I'm trying to use the bounds as the source of truth for a map created with `react-map-gl`, using PerspectiveMercatorViewport to unproject the bounds from the map. 

The result I'm getting when creating a viewport from the produced bounds is not what I expect. 

Here's a minimal test case to show my confusion...

```
const vp = new PerspectiveMercatorViewport({ 
  width: 500, 
  height: 500, 
  latitude: 0, 
  longitude: 0, 
  zoom: 10 
});
console.log(vp.latitude, vp.longitude);
// prints `0 0`
const bounds = [
  vp.unproject([0, 0]),
  vp.unproject([500, 0]),
  vp.unproject([500, 500]),
  vp.unproject([0, 500])
];
const newVp = vp.fitBounds(bounds, bounds);
console.log(newVp.latitude, newVp.longitude);
// prints 0.17166112013852455 -0.0003433227543000785
```

For my map to function I would expect fitBounds to produce a viewport identical to the original one.

Perhaps this is not the correct approach or I'm missing something important in order to use `viewport-mercator-project`, I would appreciate any help.

**Comment by bessey** [comment]
Why are you calling fitBounds with (bounds, bounds)? also, fitBounds takes 2 coordinates, not 4. E.g. `fitBounds([[0,0], [50,50]])`

**Comment by Jivings** [comment]
You were right, using two arguments worked much better thanks! 😅

Also, when unprojecting I needed to subtract a pixel meaning the final code ended up like;

```
const bounds = [
  vp.unproject([0, 0]),
  vp.unproject([499, 0]),
  vp.unproject([499, 499]),
  vp.unproject([0, 499])
];
const newVp = vp.fitBounds(bounds);
```
