### ISSUE TITLE
this.projectFlat([-38, 145]) returns NaN

### ISSUE THREAD

**Issue by lyonzy** [uber-common/viewport-mercator-project#61]
Hi,

I'm using this as part of Apache Superset and the coordinates in my dataset ([-38, 145]) seem to be returning [201.95555555555555, NaN] which is causing an error in Superset. The culprit seems to be Math.tan returning a negative value and that then being passed to Math.long. 

Are you able to confirm my data is correct, i.e. [-38, 145] are valid lat/long coordinates, or whether this is a bug?

Cheers,
Matt

**Comment by ibgreen** [comment]
@lyonzy Coordinates are specified as `[lng, lat]` (think of `[x, y]` to remember the order) 
* lng goes from -180 to 180. 
* lat goes from -85.051129 to 85.051129.

For details see e.g. https://en.wikipedia.org/wiki/Web_Mercator.

I updated the docs on master accordingly: https://github.com/uber-common/viewport-mercator-project/blob/master/docs/get-started/coordinates.md.

**Comment by lyonzy** [comment]
Ahh, I just realised I had Latitude/Longitude swapped in the Superset dashboard... *facepalm*

Thanks for your help though :)
