### ISSUE TITLE
fitBounds offset doesn't work

### ISSUE THREAD

**Issue by christinechou** [uber-common/viewport-mercator-project#89]
Glancing at `fit-bounds.js`, padding will always be the same for top/left/bottom/right. 

The problem is on line 83-84 when calculating offsetX/offsetY, the offset will *always* be 0 because padding.right - padding.left (and same for top/bottom) will always be 0, therefore the offset" option in `fitBounds` will never actually offset the map..

Also a smaller issue but the usage for `fitBounds` in the docs is a bit out of date, so I added the label. Thanks for looking into it!

**Comment by marek-sed** [comment]
Is this actually fixed?
